In [8]:
import numpy as np

# Day numbers and steps walked
day_number = np.arange(1, 11)
steps_walked = [6012, 7079, 6886, 7230, 4598, 5564, 6971, 7763, 8032, 9569]

# Create a 2D array where each row is [day_number, steps_walked]
arr = np.array([day_number, steps_walked]).T

print(arr)

[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]


In [ ]:
Represent the above data in a 10x2 array. In each row,
the first element should contain day number and
second element should contain steps walked.


In [9]:
print(arr)
# Perform the operation
new_arr = arr[:, 1] + 2000
arr[:, 1] = new_arr

print(arr)

[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]
[[    1  8012]
 [    2  9079]
 [    3  8886]
 [    4  9230]
 [    5  6598]
 [    6  7564]
 [    7  8971]
 [    8  9763]
 [    9 10032]
 [   10 11569]]


In [10]:
new_arr= arr[:,1] + 2000
arr[:,1]=new_arr
print(arr)

[[    1 10012]
 [    2 11079]
 [    3 10886]
 [    4 11230]
 [    5  8598]
 [    6  9564]
 [    7 10971]
 [    8 11763]
 [    9 12032]
 [   10 13569]]


In [11]:
matched = arr[:,1]>9000
matched
new_arr = arr[matched]
print(new_arr)

[[    1 10012]
 [    2 11079]
 [    3 10886]
 [    4 11230]
 [    6  9564]
 [    7 10971]
 [    8 11763]
 [    9 12032]
 [   10 13569]]


In [12]:
sortedArr = arr[arr[:,1].argsort()]
print('Sorted 2D Numpy Array')
print(sortedArr)

Sorted 2D Numpy Array
[[    5  8598]
 [    6  9564]
 [    1 10012]
 [    3 10886]
 [    7 10971]
 [    2 11079]
 [    4 11230]
 [    8 11763]
 [    9 12032]
 [   10 13569]]
